---
title: "Tidyr 101"
author: "Fabrice Rossi"
format: html
---

```{r}
#| message: false
here::i_am("dm-course-git-101.Rproj")
library(here)
```

```{r}
#| message: false
library(ggplot2)
library(dplyr)
library(tidyr)
```


```{r}
data("EuStockMarkets")
```

## Displaying one time series

```{r}
ggplot(EuStockMarkets, aes(x=time(EuStockMarkets), y=DAX)) +
  geom_line()
```

```{r}
EuStockMarkets <- 
  EuStockMarkets |> 
    as_tibble() |>  ## could be as.data.frame
    mutate(date = as.numeric(time(EuStockMarkets)))
```


```{r}
ggplot(EuStockMarkets, aes(x=date, y=DAX)) +
  geom_line()
```
```{r}
ggplot(EuStockMarkets, aes(x=date, y=CAC)) +
  geom_line()
```

## Two indexes on the same graphical representation ?

### Poor man's solution

```{r}
ggplot(EuStockMarkets, aes(x=date, y=CAC)) +
  geom_line(colour = "steelblue") +
  geom_line(mapping=aes(y=DAX), colour = "salmon")
```
### Tidyr solution

```{r}
EuStockMarkets |>
  pivot_longer(!date, names_to = "index") |>
  slice_head(n=10) |>
  knitr::kable()
```

```{r}
EuStockMarkets |>
  pivot_longer(!date, names_to = "index") |>
  ggplot(aes(x=date, y=value, colour=index)) +
  geom_line()
```
### More pivoting

```{r}
EuStockMarkets |>
  pivot_longer(everything()) |>
  slice_head(n=10) |>
  knitr::kable()
```

```{r}
EuStockMarkets |>
  pivot_longer(DAX | SMI) |>
  slice_head(n=10) |>
  knitr::kable()
```

### Working on rows with pivoting

```{r}
EuStockMarkets |> 
  select(!FTSE) |>
  pivot_longer(!date) |> 
  summarise(avg_stock = mean(value), .by = date) |> 
  slice_head(n=10) |>
  knitr::kable()
```

### Alternative with `rowwise`.

```{r}
EuStockMarkets |>
  select(!FTSE) |>
  rowwise() |>
  summarise(date, avg_stock = mean(c(DAX, SMI, CAC)))
```

## Reverse operation: pivot to a wider format

```{r}
EuLong <- 
  EuStockMarkets |>
    pivot_longer(!date)
```

```{r}
EuLong |>
  pivot_wider() |>
  slice_head(n=10) |>
  knitr::kable()
```

```{r}
EuLong |>
  pivot_wider(id_cols=date) |>
  slice_head(n=10) |>
  knitr::kable()
```

```{r}
data("diamonds")
dgroup <- 
  diamonds |>
  summarise(count = n(), median_price=median(price), .by=c(cut, color))
```

```{r}
dgroup |>
  pivot_wider(id_cols = cut, names_from = color, values_from = median_price)
```

Missing data support
```{r}
set.seed(42)
dgroup |>
  slice_sample(n=25) |>
  pivot_wider(id_cols = cut, names_from = color, values_from = count)
```

